baseURL = 'https://swrnv-qc.github.io/'
locale = 'en-US'
title = 'swrnv-qc'
theme = 'terminal'

[params]
  subtitle = 'Gen AI + Backend Engineer | LLM pipelines, vector search, full-stack systems'
  keywords = ['Gen AI', 'Backend Engineer', 'LangChain', 'LangGraph', 'Qdrant', 'FastAPI', 'Python', 'Go', 'Burr']

[params.logo]
  logoText = "Swrnv-qc"
  logoHomeLink = "/"

[params.twitter]
  site = '@swrnv_qc'
  creator = '@swrnv_qc'

[menu]
  [[menu.main]]
    identifier = "resume"
    name = "Resume"
    url = "https://swrnv-qc.github.io/resume/"
    weight = 1
